package main

import (
	// "fmt"
	strconv "strconv"
)

// This code is generated by 'csvgen'
// Do not edit

// UnmarshalCSV Foo func
func (this *Foo) UnmarshalCSV(in []string) error {
	// defer func() {
	// 	if r := recover(); r != nil {
	// 		fmt.Println("Recovered in Unmarshal", r)
	// 		fmt.Printf("%#v\n", in)
	// 	}
	// }()
	i := 0
	this.a = in[i]
	i++
	if x, err := strconv.ParseFloat(in[i], 64); err != nil {
		return err
	} else {
		this.b = x
	}
	return nil
}

// MarshalCSV Foo func
func (this Foo) MarshalCSV() ([]string, error) {
	out := []string{}
	out = append(out, this.a)
	out = append(out, strconv.FormatFloat(float64(this.b), 'f', -1, 64))
	return out, nil
}
